apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - role.yaml
  - user.yaml
  - group.yaml
  - groupmembership.yaml
  - userinvitation.yaml
  - protectedresource.yaml
  - policybinding.yaml
  - userpreference.yaml
  - userdeactivation.yaml
  - platformaccessapproval.yaml
  - platformaccessrejection.yaml
  - platforminvitation.yaml

