apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: iam.miloapis.com-user
spec:
  serviceRef:
    name: "iam.miloapis.com"
  kind: User
  plural: users
  singular: user
  permissions:
    - list
    - get
    - create
    - update
    - delete
    - patch
    - watch
