apiVersion: v1
kind: Secret
metadata:
  name: milo-apiserver-auth-tokens
type: Opaque
stringData:
  tokens.csv: |
    test-admin-token,admin,admin,"system:masters"
    test-user-token,test-user,1002,"system:authenticated"
