apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: notification.miloapis.com-contact
spec:
  serviceRef:
    name: "notification.miloapis.com"
  kind: Contact
  plural: contacts
  singular: contact
  permissions:
    - list
    - get
    - create
    - update
    - delete
    - patch
    - watch
  parentResources:
    - apiGroup: iam.miloapis.com
      kind: User
