apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - email.yaml
  - emailbroadcast.yaml
  - emailtemplate.yaml
  - contact.yaml
  - contactgroup.yaml
  - contactgroupmembership.yaml
  - contactgroupmembershipremoval.yaml
  - document.yaml
  - documentrevision.yaml
  - documentacceptance.yaml
