---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  name: userinvitations.iam.miloapis.com
spec:
  group: iam.miloapis.com
  names:
    kind: UserInvitation
    listKind: UserInvitationList
    plural: userinvitations
    singular: userinvitation
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.email
      name: Email
      type: string
    - jsonPath: .spec.expirationDate
      name: Expiration Date
      type: string
    - jsonPath: .status.conditions[?(@.type=='Ready')].status
      name: Ready
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: UserInvitation is the Schema for the userinvitations API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: UserInvitationSpec defines the desired state of UserInvitation
            properties:
              email:
                description: The email of the user being invited.
                type: string
                x-kubernetes-validations:
                - message: email type is immutable
                  rule: type(oldSelf) == null_type || self == oldSelf
              expirationDate:
                description: |-
                  ExpirationDate is the date and time when the UserInvitation will expire.
                  If not specified, the UserInvitation will never expire.
                format: date-time
                type: string
                x-kubernetes-validations:
                - message: expirationDate type is immutable
                  rule: type(oldSelf) == null_type || self == oldSelf
              familyName:
                description: The last name of the user being invited.
                type: string
                x-kubernetes-validations:
                - message: familyName type is immutable
                  rule: type(oldSelf) == null_type || self == oldSelf
              givenName:
                description: The first name of the user being invited.
                type: string
                x-kubernetes-validations:
                - message: givenName type is immutable
                  rule: type(oldSelf) == null_type || self == oldSelf
              invitedBy:
                description: InvitedBy is the user who invited the user. A mutation
                  webhook will default this field to the user who made the request.
                properties:
                  name:
                    description: Name is the name of the User being referenced.
                    type: string
                required:
                - name
                type: object
                x-kubernetes-validations:
                - message: invitedBy type is immutable
                  rule: type(oldSelf) == null_type || self == oldSelf
              organizationRef:
                description: OrganizationRef is a reference to the Organization that
                  the user is invoted to.
                properties:
                  name:
                    description: Name is the name of resource being referenced
                    type: string
                required:
                - name
                type: object
                x-kubernetes-validations:
                - message: organizationRef type is immutable
                  rule: type(oldSelf) == null_type || self == oldSelf
              roles:
                description: The roles that will be assigned to the user when they
                  accept the invitation.
                items:
                  description: RoleReference contains information that points to the
                    Role being used
                  properties:
                    name:
                      description: Name is the name of resource being referenced
                      type: string
                    namespace:
                      description: Namespace of the referenced Role. If empty, it
                        is assumed to be in the PolicyBinding's namespace.
                      type: string
                  required:
                  - name
                  type: object
                maxItems: 100
                minItems: 1
                type: array
                x-kubernetes-validations:
                - message: roles type is immutable
                  rule: type(oldSelf) == null_type || self == oldSelf
              state:
                description: |-
                  State is the state of the UserInvitation. In order to accept the invitation, the invited user
                  must set the state to Accepted.
                enum:
                - Pending
                - Accepted
                - Declined
                type: string
                x-kubernetes-validations:
                - message: state can only transition from Pending to another state
                    and is immutable afterwards
                  rule: type(oldSelf) == null_type || oldSelf == 'Pending' || self
                    == oldSelf
            required:
            - email
            - organizationRef
            - roles
            - state
            type: object
          status:
            description: UserInvitationStatus defines the observed state of UserInvitation
            properties:
              conditions:
                default:
                - lastTransitionTime: "1970-01-01T00:00:00Z"
                  message: Waiting for control plane to reconcile
                  reason: Unknown
                  status: Unknown
                  type: Unknown
                description: Conditions provide conditions that represent the current
                  status of the UserInvitation.
                items:
                  description: Condition contains details for one aspect of the current
                    state of this API Resource.
                  properties:
                    lastTransitionTime:
                      description: |-
                        lastTransitionTime is the last time the condition transitioned from one status to another.
                        This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: |-
                        message is a human readable message indicating details about the transition.
                        This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: |-
                        observedGeneration represents the .metadata.generation that the condition was set based upon.
                        For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                        with respect to the current state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: |-
                        reason contains a programmatic identifier indicating the reason for the condition's last transition.
                        Producers of specific condition types may define expected values and meanings for this field,
                        and whether the values are considered a guaranteed API.
                        The value should be a CamelCase string.
                        This field may not be empty.
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              inviteeUser:
                description: |-
                  InviteeUser contains information about the invitee user in the invitation.
                  This value may be nil if the invitee user has not been created yet.
                properties:
                  name:
                    description: |-
                      Name is the name of the invitee user in the invitation.
                      Name is a cluster-scoped resource, so Namespace is not needed.
                    type: string
                required:
                - name
                type: object
              inviterUser:
                description: InviterUser contains information about the user who invited
                  the user in the invitation.
                properties:
                  displayName:
                    description: DisplayName is the display name of the user who invited
                      the user in the invitation.
                    type: string
                  emailAddress:
                    description: EmailAddress is the email address of the user who
                      invited the user in the invitation.
                    type: string
                type: object
              organization:
                description: Organization contains information about the organization
                  in the invitation.
                properties:
                  displayName:
                    description: DisplayName is the display name of the organization
                      in the invitation.
                    type: string
                type: object
            type: object
        type: object
    selectableFields:
    - jsonPath: .status.inviteeUser.name
    served: true
    storage: true
    subresources:
      status: {}
