apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: crm.miloapis.com-note
spec:
  serviceRef:
    name: "crm.miloapis.com"
  kind: Note
  plural: notes
  singular: note
  permissions:
    - list
    - get
    - create
    - update
    - delete
    - patch
    - watch
