kind: CustomResourceStateMetrics
spec:
  resources:
    - groupVersionKind:
        group: "iam.miloapis.com"
        kind: "PolicyBinding"
        version: "v1alpha1"
      labelsFromPath:
        name: [metadata, name]
        namespace: [metadata, namespace]
      metricNamePrefix: milo_policy_bindings
      metrics:
        - name: "info"
          each:
            type: Info
            info:
              labelsFromPath:
                "uid": [metadata, uid]
        - name: "created_timestamp"
          each:
            type: Gauge
            gauge:
              path: [metadata, creationTimestamp]