apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# Aggregates all custom resource metrics configurations from Milo services.
components:
  - ../services/quota/telemetry/metrics/control-plane
  - ../services/iam/telemetry/metrics/control-plane
  - ../services/notification/telemetry/metrics/control-plane
  - ../services/resource-manager/telemetry/metrics/control-plane
