# This the IAM role definition for a new created user
roleId: userSelfManage
parent: services/iam.datumapis.com
name: services/iam.datumapis.com/roles/userSelfManage
displayName: IAM Self User Managing Role
spec:
  includedPermissions:
  - iam.datumapis.com/users.get
  - iam.datumapis.com/users.update
  - iam.datumapis.com/users.delete
