apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: identity-user-session-viewer
  annotations:
    kubernetes.io/display-name: Identity User-Session Viewer
    kubernetes.io/description: "Allows viewing user sessions and user identities."
spec:
  launchStage: Beta
  includedPermissions:
  - identity.miloapis.com/sessions.list
  - identity.miloapis.com/sessions.get
  - identity.miloapis.com/useridentities.list
  - identity.miloapis.com/useridentities.get
