apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - owner.yaml
  - project-manager.yaml
  - iam-viewer.yaml
  - iam-editor.yaml
  - iam-admin.yaml
  - resourcemanager-reader.yaml
  - resourcemanager-editor.yaml
  - resourcemanager-admin.yaml
  - core-reader.yaml
  - core-editor.yaml
  - core-admin.yaml
  - apiextensions-reader.yaml
  - iam-user-self-manage.yaml
  - iam-user-preferences-manager.yaml
  - iam-user-deactivations-reader.yaml
  - iam-user-deactivations-editor.yaml
  - iam-user-deactivations-admin.yaml
  - notification-email-reader.yaml
  - notification-email-creator.yaml
  - notification-email-admin.yaml
  - notification-email-broadcast-reader.yaml
  - notification-email-broadcast-creator.yaml
  - notification-email-broadcast-admin.yaml
  - notification-contact-reader.yaml
  - notification-contact-editor.yaml
  - notification-contact-admin.yaml
  - notification-contact-group-reader.yaml
  - notification-contact-group-editor.yaml
  - notification-contact-group-admin.yaml
  - notification-contact-group-membership-reader.yaml
  - notification-contact-group-membership-editor.yaml
  - notification-contact-group-membership-admin.yaml
  - iam-user-invitations-reader.yaml
  - iam-user-invitations-editor.yaml
  - iam-user-invitations-admin.yaml
  - notification-contact-group-membership-removal-reader.yaml
  - notification-contact-group-membership-removal-editor.yaml
  - notification-contact-group-membership-removal-admin.yaml
  - organizationmembership-reader.yaml
  - organizationmembership-editor.yaml
  - organizationmembership-admin.yaml
  - organizationmembership-self-delete.yaml
  - iam-role-reader.yaml
  - iam-role-editor.yaml
  - iam-role-admin.yaml
  - organization-viewer.yaml
  - organization-admin.yaml
  - project-viewer.yaml
  - project-admin.yaml
  - iam.miloapis.com-getinvitation.yaml
  - iam.miloapis.com-acceptinvitation.yaml
  - iam-platform-access-approvals-reader.yaml
  - iam-platform-access-approvals-editor.yaml
  - iam-platform-access-approvals-admin.yaml
  - iam-platform-access-rejections-reader.yaml
  - iam-platform-access-rejections-editor.yaml
  - iam-platform-access-rejections-admin.yaml
  - iam-platform-invitations-reader.yaml
  - iam-platform-invitations-editor.yaml
  - iam-platform-invitations-admin.yaml
  - crm-note-viewer.yaml
  - crm-note-creator.yaml
  - crm-note-editor.yaml
  - crm-note-creator-editor.yaml
  - crm-note-admin.yaml
  - identity-user-session-viewer.yaml