apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: organizationmembership-self-delete
  annotations:
    kubernetes.io/display-name: Organization Membership Self Delete
    kubernetes.io/description: "Allows a user to delete their own organization membership"
spec:
  launchStage: Beta
  includedPermissions:
    - resourcemanager.miloapis.com/organizationmemberships.get
    - resourcemanager.miloapis.com/organizationmemberships.list
    - resourcemanager.miloapis.com/organizationmemberships.delete


